<a href="https://colab.research.google.com/github/Chandrashekar0123/Lerno-DL-case-study/blob/DeepLearning-Models/RNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.utils import to_categorical


In [ ]:
# Sample text
text = "This is a sample text for language modeling. We'll use it to train an RNN."


In [ ]:
# Create a mapping of unique characters to integers
chars = sorted(list(set(text)))
char_to_idx = {char: idx for idx, char in enumerate(chars)}
idx_to_char = {idx: char for char, idx in char_to_idx.items()}


In [ ]:
chars

[' ',
 "'",
 '.',
 'N',
 'R',
 'T',
 'W',
 'a',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'l',
 'm',
 'n',
 'o',
 'p',
 'r',
 's',
 't',
 'u',
 'x']

In [ ]:
# Convert text to integer sequences
sequences = [char_to_idx[char] for char in text]


In [ ]:
sequences

[5,
 12,
 13,
 20,
 0,
 13,
 20,
 0,
 7,
 0,
 20,
 7,
 15,
 18,
 14,
 9,
 0,
 21,
 9,
 23,
 21,
 0,
 10,
 17,
 19,
 0,
 14,
 7,
 16,
 11,
 22,
 7,
 11,
 9,
 0,
 15,
 17,
 8,
 9,
 14,
 13,
 16,
 11,
 2,
 0,
 6,
 9,
 1,
 14,
 14,
 0,
 22,
 20,
 9,
 0,
 13,
 21,
 0,
 21,
 17,
 0,
 21,
 19,
 7,
 13,
 16,
 0,
 7,
 16,
 0,
 4,
 3,
 3,
 2]

In [ ]:
idx_to_char

{0: ' ',
 1: "'",
 2: '.',
 3: 'N',
 4: 'R',
 5: 'T',
 6: 'W',
 7: 'a',
 8: 'd',
 9: 'e',
 10: 'f',
 11: 'g',
 12: 'h',
 13: 'i',
 14: 'l',
 15: 'm',
 16: 'n',
 17: 'o',
 18: 'p',
 19: 'r',
 20: 's',
 21: 't',
 22: 'u',
 23: 'x'}

In [ ]:
char_to_idx

{' ': 0,
 "'": 1,
 '.': 2,
 'N': 3,
 'R': 4,
 'T': 5,
 'W': 6,
 'a': 7,
 'd': 8,
 'e': 9,
 'f': 10,
 'g': 11,
 'h': 12,
 'i': 13,
 'l': 14,
 'm': 15,
 'n': 16,
 'o': 17,
 'p': 18,
 'r': 19,
 's': 20,
 't': 21,
 'u': 22,
 'x': 23}

In [ ]:
# Parameters
sequence_length = 10 # You can change this value
chars=sorted(list(set(text)))
vocab_size = len(chars)


In [ ]:
vocab_size

24

In [ ]:
#We'll create sequences of 10 characters and have the model predict the next character.
# Prepare input/output pairs
X = []
y = []
for i in range(0, len(sequences) - sequence_length):
  X.append(sequences[i:i+sequence_length])
  y.append(sequences[i+sequence_length])
X = np.array(X)
y = np.array(y)


In [ ]:
i

63

In [ ]:
X

array([[ 5, 12, 13, 20,  0, 13, 20,  0,  7,  0],
       [12, 13, 20,  0, 13, 20,  0,  7,  0, 20],
       [13, 20,  0, 13, 20,  0,  7,  0, 20,  7],
       [20,  0, 13, 20,  0,  7,  0, 20,  7, 15],
       [ 0, 13, 20,  0,  7,  0, 20,  7, 15, 18],
       [13, 20,  0,  7,  0, 20,  7, 15, 18, 14],
       [20,  0,  7,  0, 20,  7, 15, 18, 14,  9],
       [ 0,  7,  0, 20,  7, 15, 18, 14,  9,  0],
       [ 7,  0, 20,  7, 15, 18, 14,  9,  0, 21],
       [ 0, 20,  7, 15, 18, 14,  9,  0, 21,  9],
       [20,  7, 15, 18, 14,  9,  0, 21,  9, 23],
       [ 7, 15, 18, 14,  9,  0, 21,  9, 23, 21],
       [15, 18, 14,  9,  0, 21,  9, 23, 21,  0],
       [18, 14,  9,  0, 21,  9, 23, 21,  0, 10],
       [14,  9,  0, 21,  9, 23, 21,  0, 10, 17],
       [ 9,  0, 21,  9, 23, 21,  0, 10, 17, 19],
       [ 0, 21,  9, 23, 21,  0, 10, 17, 19,  0],
       [21,  9, 23, 21,  0, 10, 17, 19,  0, 14],
       [ 9, 23, 21,  0, 10, 17, 19,  0, 14,  7],
       [23, 21,  0, 10, 17, 19,  0, 14,  7, 16],
       [21,  0, 10, 

In [ ]:
y

array([20,  7, 15, 18, 14,  9,  0, 21,  9, 23, 21,  0, 10, 17, 19,  0, 14,
        7, 16, 11, 22,  7, 11,  9,  0, 15, 17,  8,  9, 14, 13, 16, 11,  2,
        0,  6,  9,  1, 14, 14,  0, 22, 20,  9,  0, 13, 21,  0, 21, 17,  0,
       21, 19,  7, 13, 16,  0,  7, 16,  0,  4,  3,  3,  2])

In [ ]:
# One-hot encode the target (y)
y = to_categorical(y, num_classes=vocab_size)


In [ ]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [ ]:
# Build the RNN model
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=64, input_length=sequence_length))
model.add(SimpleRNN(128, return_sequences=False))
model.add(Dense(vocab_size, activation='softmax'))


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
# Model summary
model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ simple_rnn (SimpleRNN)               │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


In [ ]:
# Train the model
model.fit(X, y, batch_size=64, epochs=50)


Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.0938 - loss: 3.1713
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 0.2031 - loss: 3.1097
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3125 - loss: 3.0487
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.4375 - loss: 2.9854
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5469 - loss: 2.9173
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6094 - loss: 2.8426
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6406 - loss: 2.7594
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6406 - loss: 2.6673
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6406 - loss: 2.5673
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6094 - loss: 2.4627
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5312 - loss: 2.3579
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 2.2540
Ep

In [ ]:
def generate_text(seed_text, num_chars):
  for _ in range(num_chars):
# Convert seed_text to integer sequences
    input_seq = [char_to_idx[char] for char in seed_text[-sequence_length:]]
    input_seq = np.reshape(input_seq, (1, sequence_length))
# Predict the next character
    predicted = model.predict(input_seq, verbose=0)
    predicted_char = idx_to_char[np.argmax(predicted)]
# Add the predicted character to the seed text
    seed_text += predicted_char
  return seed_text


In [ ]:
# Generate new text
seed = "This is a "
generated_text = generate_text(seed, 500)
print(generated_text)


This is a sample text for language modeling. We'll use it to train an RNN. utd laate in mod.naan. We'eo.nse in teeerain  naaNN. e  o. it t  te in Rn  nain ane mo. uing. Weeli use ialt  tr ln in RN  rul   a  l to  te loan  an lNene ie  oanrain   eeeN. e   l ate    lot.aa   ageaN.   telt.te  l  oaen   o  e.ne at  laneat.  moeet.ng  We aaeeg  t x. ang l xgelde lo gr og mo tg nee W an  oa. iine  o.el  ge teeto ls inaan lrpl N.e lo toate at aN .eate l ntet.a mo e aag. W  uldnse i  to'erain aneeNN. ut ol ate ia
